[tool.poetry]
name = "codes"
version = "0.1.0"
description = ""
authors = ["patryk <gryzabawy@o2.pl>"]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.3"
pytest = "^8.3.5"
ruff = "^0.11.2"
mypy = "^1.15.0"
python-dotenv = "^1.0.1"
pgeocode = "^0.5.0"
ortools = "^9.12.4544"
pydantic = "^2.10.6"
geopandas = "^1.0.1"
matplotlib = "^3.10.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
extend-select = ["C4", "SIM", "TCH"]

[tool.ruff.format]
quote-style = "single"
skip-magic-trailing-comma = true

[tool.mypy]
allow_redefinition = true

[[tool.mypy.overrides]]
module = ["pgeocode.*"]
follow_untyped_imports = true
#ignore_missing_imports = true

[tool.pytest.ini_options]
filterwarnings = [
#    "error",
#    "ignore::UserWarning",
#    # note the use of single quote below to denote "raw" strings in TOML
#    'ignore:function ham\(\) is deprecated:DeprecationWarning',
    "ignore::DeprecationWarning"
]